// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyacvtaqiyathjblhgqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5YWN2dGFxaXlhdGhqYmxoZ3FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzQxNjAsImV4cCI6MjA2NDcxMDE2MH0.SJsXe3QGBLkQ77trNuTH0bdREqBy38uelWQgbsMr-KE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);